const Map<String, Map<String, String>> lang = {
  'en': {
    'home': 'Home',
    'query': 'Query',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'assignments': 'Assignments',
    'notice_board': 'Notice Board',
    'events': 'Events',
    'results': 'Results',
    'prizes': 'Prizes',
    'teachers': 'Teachers',
    'change_language': 'Change Language',
    'student_name': 'Student Name',
    'parent_name': 'Parent Name',
    'parent_email': 'parent.email@example.com',
    'phone_number': 'Phone Number',
    'address': 'Address',
    'class_section': 'Class & Section',
    'academic_year': 'Academic Year',
    'edit_profile': 'Edit Profile',
  },
  'hi': {
    'home': 'होम',
    'query': 'प्रश्न',
    'notifications': 'सूचनाएं',
    'profile': 'प्रोफ़ाइल',
    'assignments': 'असाइनमेंट',
    'notice_board': 'सूचना पट्ट',
    'events': 'घटनाएँ',
    'results': 'परिणाम',
    'prizes': 'पुरस्कार',
    'teachers': 'शिक्षक',
    'change_language': 'भाषा बदलें',
    'student_name': 'छात्र का नाम',
    'parent_name': 'अभिभावक का नाम',
    'parent_email': 'parent.email@example.com',
    'phone_number': 'फ़ोन नंबर',
    'Phone_number': 'फ़ोन नंबर',
    'address': 'पता',
    'class_section': 'कक्षा और अनुभाग',
    'academic_year': 'शैक्षणिक वर्ष',
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
  },
};
