const Map<String, Map<String, String>> lang = {
  'en': {
    'home': 'Home',
    'query': 'Query',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'assignments': 'Assignments',
    'subject': 'Subject',
    'title': 'Title',
    'due_date': 'Due Date',
    'status': 'Status',
    'action': 'Action',
    'view_details': 'View Details',
    'search_assignments': 'Search Assignments by name',
    'submitted': '✅ Submitted',
    'not_submitted': '❌ Not Submitted',
    'student_name': 'Student Name',
    'notice_board': 'Notice Board',
    'events': 'Events',
    'results': 'Results',
    'prizes': 'Prizes',
    'teachers': 'Teachers',
    'change_language': 'Change Language',
    'attendance_viewport': 'Attendance Viewport',
    'phone_number': 'Phone Number',
    'address': 'Address',
    'class_section': 'Class & Section',
    'academic_year': 'Academic Year',
    'edit_profile': 'Edit Profile',
    'mathematics': 'Mathematics',
    'science': 'Science',
    'all': 'All',
  },
  'hi': {
    'home': 'होम',
    'query': 'प्रश्न',
    'notifications': 'सूचनाएं',
    'profile': 'प्रोफ़ाइल',
    'assignments': 'असाइनमेंट',
    'subject': 'विषय',
    'title': 'शीर्षक',
    'due_date': 'नियत तिथि',
    'status': 'स्थिति',
    'action': 'कार्य',
    'view_details': 'विवरण देखें',
    'search_assignments': 'असाइनमेंट का नाम खोजें',
    'submitted': '✅ जमा किया',
    'not_submitted': '❌ जमा नहीं किया',
    'student_name': 'छात्र का नाम',
    'notice_board': 'सूचना पट्ट',
    'events': 'घटनाएँ',
    'results': 'परिणाम',
    'prizes': 'पुरस्कार',
    'teachers': 'शिक्षक',
    'change_language': 'भाषा बदलें',
    'attendance_viewport': 'उपस्थिति व्यूपोर्ट',
    'phone_number': 'फ़ोन नंबर',
    'address': 'पता',
    'class_section': 'कक्षा और अनुभाग',
    'academic_year': 'शैक्षणिक वर्ष',
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
    'mathematics': 'गणित',
    'science': 'विज्ञान',
    'all': 'सभी',
  },
};
